### ISSUE TITLE
Token not found when using strava

### ISSUE THREAD

**Issue by cz8s** [MaikuB/flutter_appauth#6]
Hi,

we are trying to use flutter_appauth to authenticate to strava.com
We changed the example to login to strava. The request to strava works,
we see the strava website, can authorize, and get redirected to the app.
But the response we get in the app is empty.
Specifically, the error is:
```
 PlatformException(token_failed, Failed to get token, null)
```
on android and this on ios:
``` 
PlatformException(authorize_and_exchange_code failed, Failed to authorize, null)
```

Since we are new to this flutter thingy, we don't really know how to debug this.
Do you have any hints where to look? 

I don't know if this matters, but strava does not support discovery urls,
so we use AuthorizationTokenRequest and explicitly specify the client_id and redirect_url.

Thanks a lot

**Comment by MaikuB** [comment]
I've released a new version that should give back some more details about the error (just extract more info from the AppAuth exception class). Don't know that will help you any further though. The error you're seeing would indicate a problem with exchanging the authorisation code for a token. Hard to say why though given each oAuth server can be different. If you wanted to debug, you could clone the repo and reference it in your app by the [path](https://www.dartlang.org/tools/pub/dependencies#path-packages). This would allow you to put breakpoints on the Android and iOS side. Perhaps there are extra parameters you should be passing in for this to work with Strava.

You're always going to need to specify the client id and redirect url. If discovery isn't supported then you need to specify the authorisation and token endpoints

**Comment by cz8s** [comment]
Hi,

just a little update: It still does not work. But at this point we think this might be because strava uses a different flow. Will keep you updated. But thanks for your reply. Very much apreciated :)

**Comment by MaikuB** [comment]
Closing this due to lack of further response. I'm not familiar with Strava but doing a quick search on their docs shows that they require `approval_prompt` to be specified. I believe you should be able to do this passing it as one of the additional parameters

**Comment by dirkrob** [comment]
Did you get this issue resolved, I am having the same issue stuck at authorize with the same response you have, if you can point me in a direction it will help a great deal thx
